[package]
name = "dash_rust"
version = "0.1.0"
authors = ["Hajime Fukuda <hajime.fukuda@me.com>"]

[dependencies]
pcap = { version = "0.7", features = ["tokio"] }

[dependencies.pnet]
version = "0.19.0"
